services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mugloar-bot

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mugloar-frontend
    ports:
      - "3000:80"
